CREATE DATABASE IF NOT EXISTS "greenhouses"


-- Users
CREATE TABLE IF NOT EXISTS Users_(
    id UUID PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    createdAt TIMESTAMP,
    updatedAt TIMESTAMP
)

DROP TABLE IF EXISTS Users_;

DROP TABLE IF EXISTS refresh_tokens;

-- Access
CREATE TYPE ACCESS_TYPES AS ENUM ('ADMIN', 'READONLY');

CREATE TABLE IF NOT EXISTS User_access(
    id UUID PRIMARY KEY,
    user_id UUID REFERENCES Users_ ON DELETE CASCADE ON UPDATE CASCADE,
    access ACCESS_TYPES,
    controller_id UUID REFERENCES Controllers ON DELETE CASCADE ON UPDATE CASCADE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
)

DROP TYPE ACCESS_TYPES;

DROP TABLE IF EXISTS accesses;


-- Controller
CREATE TABLE IF NOT EXISTS Controllers(
    id UUID PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    admin UUID NOT NULL,
    readonly UUID NOT NULL,
    description UUID REFERENCES Indexes ON DELETE CASCADE ON UPDATE CASCADE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
)

DROP TABLE IF EXISTS Controllers;


-- Indexes
CREATE TABLE IF NOT EXISTS Indexes (
    id UUID PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    tolerance UUID REFERENCES Tolerances ON DELETE CASCADE ON UPDATE CASCADE,
    values UUID REFERENCES Index_values ON DELETE CASCADE ON UPDATE CASCADE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
)

DROP TABLE IF EXISTS Indexes;


-- Index properties
CREATE TABLE IF NOT EXISTS Index_types(
    id UUID PRIMARY KEY,
    index_id UUID REFERENCES Indexes ON DELETE CASCADE ON UPDATE CASCADE,
    name TEXT NOT NULL,
    unit_of_measurement VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
)

DROP TABLE IF EXISTS Types;


-- Index values
CREATE TABLE IF NOT EXISTS Index_values(
    id UUID PRIMARY KEY,
    value NUMERIC(16, 5) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
)

DROP TABLE IF EXISTS Index_values;


-- Tolerance
CREATE TYPE DANGER_RATE_TYPES AS ENUM ('SAFETY', 'WARNING', 'DANGER');
CREATE TYPE COLOR_TYPES AS ENUM ('#f44336', '#ffca28', '#9ccc65');
CREATE TYPE LABEL_TYPES AS ENUM ('FAR BELOW NORMAL', 'BELOW NORMAL', 'NORMAL', 'ABOVE THE NORM', 'MUCH HIGHER THAN NORMAL');

CREATE TABLE IF NOT EXISTS Tolerances(
    id UUID PRIMARY KEY,
    danger_rate_alias DANGER_RATE_TYPES NOT NULL,
    hex_color COLOR_TYPES NOT NULL,
    start_value NUMERIC(16,5) NOT NULL,
    label LABEL_TYPES NOT NULL
)

DROP TYPE DANGER_RATE_TYPES;
DROP TYPE COLOR_TYPES;
DROP TYPE LABEL_TYPES;

DROP TABLE IF EXISTS Tolerances;

-- Users
TRUNCATE TABLE Users;

TRUNCATE TABLE refresh_tokens;

TRUNCATE TABLE types;

TRUNCATE TABLE indexes;

TRUNCATE TABLE controllers;

TRUNCATE TABLE keys;

TRUNCATE TABLE accesses;

TRUNCATE TABLE tolerances;

TRUNCATE TABLE values;

